# Use a base Python image
FROM python:3.9

# Set the working directory
WORKDIR /app

# Copy the Python script for the subscriber into the container
COPY subscriber.py .

# Install any required Python packages
RUN pip install paho-mqtt pymongo redis

# Define the command to run the subscriber script
CMD ["python", "subscriber.py"]
