# Use an official Python runtime as a parent image
FROM python:3.9

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Create and set the working directory in the container
WORKDIR /app

# Copy the Python script for the publisher into the container
COPY main.py .

# Install any needed packages
RUN pip install fastapi uvicorn pydantic pymongo


# Expose the port that the FastAPI app will run on (usually 8000)
EXPOSE 8000

# Command to run your FastAPI application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
